name: Build
on:
    push:
        branches:
            - master
jobs:
    build:
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Configure git user
              run: |
                  git config --global user.name 'Github'
                  git config --global user.email 'github@users.noreply.github.com'
            - name: Create Version tag
              run: yarn release
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn build
            - name: Commit Version
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git push origin HEAD:master && git push origin HEAD:master --tags
